name: "Changed Files"
description: "A simple action that retrieves the list of changed files in a pull request using the GitHub CLI and can filter using regex."

outputs:
  all_changed_files:
    description: "A space-separated list of all changed files."
    value: ${{ steps.main.outputs.all_changed_files }}
  all_changed_files_count:
    description: "The number of changed files."
    value: ${{ steps.main.outputs.all_changed_files_count }}

inputs:
  files:
    description: "File inclusion patterns as regex (one per line). Leave empty to include all files."
    required: false
    default: ""
  exclude:
    description: "File exclusion patterns as regex (one per line). Leave empty to exclude no files."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - id: main
      run: |
        if [ -z "$GH_TOKEN" ]; then
          export GH_TOKEN=$GITHUB_TOKEN
        fi

        # Remove empty lines and join non-blank lines with a pipe.
        INCLUDE_REGEX=$(echo "${{ inputs.files }}" | sed '/^[[:space:]]*$/d' | tr '\n' '|' | sed 's/|$//')
        EXCLUDE_REGEX=$(echo "${{ inputs.exclude }}" | sed '/^[[:space:]]*$/d' | tr '\n' '|' | sed 's/|$//')

        # Set default values if inputs are empty.
        if [ -z "$INCLUDE_REGEX" ]; then 
          INCLUDE_REGEX=".*"
        fi
        if [ -z "$EXCLUDE_REGEX" ]; then 
          EXCLUDE_REGEX="a^"
        fi

        echo "Using include regex: $INCLUDE_REGEX"
        echo "Using exclude regex: $EXCLUDE_REGEX"

        # Determine whether this is a pull_request event or a push event.
        if [ -n "${{ github.event.pull_request.number }}" ]; then
          echo "Detected pull_request event."
          FILES=$(gh api --paginate repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files -q \
            '.[] | select(.status == "removed" | not) | .filename' || true)
        else
          echo "Detected push event. Using compare API."
          FILES=$(gh api repos/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.sha }}/files -q \
            '.files[].filename' 2>/dev/null || true)
          # If the compare API returns an error response (starting with '{'), fallback to git diff.
          FIRST_CHAR=$(echo "$FILES" | head -c 1)
          if [ "$FIRST_CHAR" = "{" ]; then
            echo "Compare API returned an error. Falling back to git diff."
            FILES=$(git diff --name-only "${{ github.event.before }}" "${{ github.sha }}" || true)
          fi
        fi

        FILES=$(echo "$FILES" | grep -E "$INCLUDE_REGEX" || true)
        FILES=$(echo "$FILES" | grep -E -v "$EXCLUDE_REGEX" || true)

        # Remove completely empty lines.
        FILES=$(echo "$FILES" | sed '/^[[:space:]]*$/d')
        # Convert the list to a single space-separated line.
        FILES=$(echo "$FILES" | xargs)

        echo "Got files: [$FILES]"

        COUNT=$(echo "$FILES" | wc -w)

        # Write outputs for this step.
        echo "all_changed_files=$FILES" >> "$GITHUB_OUTPUT"
        echo "all_changed_files_count=$COUNT" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
